server:
  port: 1111
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
  jpa:
    show-sql: true
  application:
    name: ORDER-SERVICE  
    

      
    
    
   